name: Docker Build and Push

on:
  push:
    tags:
      - 'v*.*.*'  # Se ejecuta cuando se hace un push con una etiqueta como 'v1.1.1'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Revisar el c칩digo
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Configurar Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Iniciar sesi칩n en Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Obtener la versi칩n desde la etiqueta
      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      # 5. Construir la imagen Docker
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/welcome-to-docker:${{ env.VERSION }} .

      # 6. Etiquetar la imagen como 'latest'
      - name: Tag Docker image as latest
        run: docker tag ${{ secrets.DOCKER_USERNAME }}/welcome-to-docker:${{ env.VERSION }} ${{ secrets.DOCKER_USERNAME }}/welcome-to-docker:latest

      # 7. Subir las im치genes a Docker Hub
      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/welcome-to-docker:${{ env.VERSION }}
          docker push ${{ secrets.DOCKER_USERNAME }}/welcome-to-docker:latest
